"use strict";
var keywords = {
    cr: 'CREATE',
    tb: 'TABLE',
    pk: 'PRIMARY KEY',
    ins: 'INSERT',
    sel: 'SELECT',
    fr: 'FROM',
    alt: 'ALTER',
    dst: 'DISTINCT',
    up: 'UPDATE',
    dl: 'DELETE',
    tr: 'TRUNCATE',
    ob: 'ORDER BY',
    bt: 'BETWEEN',
    wh: 'WHERE',
    li: 'LIMIT',
    inl: 'IS NULL',
    d: 'DROP',
    dc: 'DROP COLUMN',
    dd: 'DROP DATABASE',
    dt: 'DROP TABLE',
    gb: 'GROUP BY',
    hv: 'HAVING',
    j: 'JOIN',
    ij: 'INNER JOIN',
    lj: 'LEFT JOIN',
    rj: 'RIGHT JOIN',
    un: 'UNION',
    una: 'UNION ALL',
    ex: 'EXISTS',
    lk: 'LIKE',
    cs: 'CASE',
    th: 'THEN',
    el: 'ELSE',
};
